name: high_dim_out_gp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2.0
  - r-base
  - r-robustgasp
  - pandas
  - ipykernel
  - scikit-image
  - seaborn
  - matplotlib
  - rasterio
  - pip
  - pip:
      - -e .
      - -e ./src/pca_psimpy
