name: high_dim_out_gp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2.0
  - r-base
  - r-robustgasp
  - r-optparse
  - r-jsonlite
  - r-essentials
  - r-argparse
  - rpy2<3.6.0
  - pandas
  - ipykernel
  - scikit-image
  - seaborn
  - matplotlib
  - rasterio
  - pytest
  - pip
  - pip:
      - -e .
      - -e ./src/pca_psimpy
